### ISSUE TITLE
UnicodeError

### ISSUE THREAD

**Issue by mschirrmeister** [polaris-gslb/polaris-gslb#11]
When I start the health checker in foreground mode, I get an unicode error. Everything still seems to work, but not sure if that is a bad thing.

I have it running on a CentOS 7 system with python 3.4.3.

```
$ python3.4 -V
Python 3.4.3
```

```python
[root@omg-vm-gslb-1 bin]# /opt/polaris/bin/polaris-health -d start
2015-11-11 20:29:07,118 [INFO] polaris_health.core.reactor: starting Polaris health...
2015-11-11 20:29:07,343 [DEBUG] polaris_health.core.reactor: writting /opt/polaris/run/polaris-health.pid
Traceback (most recent call last):
  File "/usr/lib64/python3.4/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/polaris/bin/polaris-health", line 177, in <module>
    main()
  File "/opt/polaris/bin/polaris-health", line 89, in main
    start(debug=opts.d)
  File "/opt/polaris/bin/polaris-health", line 124, in start
    polaris_health.main()
  File "/usr/lib/python3.4/site-packages/polaris_gslb-0.3.1-py3.4.egg/polaris_health/__init__.py", line 26, in main
  File "/usr/lib/python3.4/site-packages/polaris_gslb-0.3.1-py3.4.egg/polaris_health/core/reactor.py", line 134, in __init__
  File "/usr/lib/python3.4/site-packages/polaris_gslb-0.3.1-py3.4.egg/polaris_health/core/reactor.py", line 180, in _heartbeat_loop
  File "/usr/lib/python3.4/site-packages/python3_memcached-1.51-py3.4.egg/memcache.py", line 573, in set
  File "/usr/lib/python3.4/site-packages/python3_memcached-1.51-py3.4.egg/memcache.py", line 799, in _set
  File "/usr/lib/python3.4/site-packages/python3_memcached-1.51-py3.4.egg/memcache.py", line 343, in _get_server
  File "/usr/lib/python3.4/site-packages/python3_memcached-1.51-py3.4.egg/memcache.py", line 1113, in connect
  File "/usr/lib/python3.4/site-packages/python3_memcached-1.51-py3.4.egg/memcache.py", line 1133, in _get_socket
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by antongavrik** [comment]
This is a critical condition due to memcached not running, please make sure memcached is up before starting polaris.

**Comment by mschirrmeister** [comment]
You are right, I started memcached later.
