### ISSUE TITLE
Unable to start after install

### ISSUE THREAD

**Issue by cbrassel** [polaris-gslb/polaris-gslb#2]
Just installed polaris-gslb on new ubuntu 14.04 / Python 3.4 installed like your wiki, if I try to start (backend or health monitor) I have this 

/opt/polaris/bin# python3 polaris-health
Traceback (most recent call last):
  File "polaris-health", line 16, in <module>
    import polaris_health
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/core/reactor.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/core/tracker.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/state/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/state/pool.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/monitors/__init__.py", line 61, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/monitors/http.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.3.0-py3.4.egg/polaris_health/protocols/http.py", line 15, in <module>
AttributeError: 'module' object has no attribute '_create_unverified_context'

Any idea ?

**Comment by cbrassel** [comment]
the default version of python is the 3.4.0 and it's not working for you, upgrade to the 3.4.3 has resolved the problem

**Comment by antongavrik** [comment]
Thank you for reporting this, updating the wiki with 3.4.3 as the minimum required version.
