### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by Ara4Sh** [polaris-gslb/polaris-gslb#24]
Hello 

in fresh installation on Debian jessie i got this error : 
```
root@site:/opt/polaris/etc# /opt/polaris/bin/polaris-health start
Starting Polaris Health... Traceback (most recent call last):
  File "/opt/polaris/bin/polaris-health-control", line 11, in <module>
    from  polaris_health import config, guardian
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/guardian/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/tracker/__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/state/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/state/pool.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/monitors/__init__.py", line 60, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/monitors/http.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/polaris_gslb-0.4.0-py3.4.egg/polaris_health/protocols/http.py", line 16, in <module>
AttributeError: 'module' object has no attribute '_create_unverified_context'
failed to start!
```

polaris-lb.yml
```
pools:
    www:
        monitor: http
        monitor_params:
            use_ssl: false
            hostname: new.site.com
            url_path: /healthcheck?check_all=true
        lb_method: wrr 
        fallback: any
        members:
        - ip: 185.155
          name: haproxy-pa
          weight: 1
        - ip: 185.155
          name: haproxy-af
          weight: 1

globalnames:
    new.site.com:
        pool: www
        ttl: 1
```
Os info : 

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie
```
pdns info : 
```
Aug 08 10:47:32 PowerDNS Authoritative Server 3.4.1 (jenkins@autotest.powerdns.com) (C) 2001-2014 PowerDNS.COM BV
Aug 08 10:47:32 Using 64-bits mode. Built on 20160510164059 by root@conan, gcc 4.9.2.
```
python info : 
```
/usr/bin/python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
```
any thing I missed in configuration? 

thank you

**Comment by antongavrik** [comment]
Python 3.4.3+ is needed

**Comment by Ara4Sh** [comment]
Thank you 

problem solved
